CREATE TABLE platform_email_settings (
    id CHAR(26) PRIMARY KEY,
    provider_code VARCHAR(40) NOT NULL,
    host VARCHAR(160) NOT NULL,
    port INT NOT NULL,
    protocol VARCHAR(16) NOT NULL,
    auth_required TINYINT(1) NOT NULL DEFAULT 0,
    starttls_enabled TINYINT(1) NOT NULL DEFAULT 1,
    ssl_enabled TINYINT(1) NOT NULL DEFAULT 0,
    username VARCHAR(160) NULL,
    password_ciphertext TEXT NULL,
    from_name VARCHAR(160) NOT NULL,
    from_email VARCHAR(160) NOT NULL,
    reply_to_email VARCHAR(160) NULL,
    connection_timeout_ms INT NOT NULL DEFAULT 10000,
    read_timeout_ms INT NOT NULL DEFAULT 10000,
    write_timeout_ms INT NOT NULL DEFAULT 10000,
    last_test_sent_at DATETIME(6) NULL,
    last_test_status VARCHAR(40) NULL,
    last_test_error VARCHAR(500) NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    created_by_user_id CHAR(26) NULL,
    updated_by_user_id CHAR(26) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    KEY idx_platform_email_settings_active (active),
    KEY idx_platform_email_settings_updated_at (updated_at)
);

CREATE TABLE platform_email_templates (
    id CHAR(26) PRIMARY KEY,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(160) NOT NULL,
    category VARCHAR(40) NOT NULL,
    description VARCHAR(500) NULL,
    subject_template VARCHAR(500) NOT NULL,
    html_template LONGTEXT NOT NULL,
    text_template LONGTEXT NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    created_by_user_id CHAR(26) NULL,
    updated_by_user_id CHAR(26) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    UNIQUE KEY uk_platform_email_templates_code (code),
    KEY idx_platform_email_templates_category (category),
    KEY idx_platform_email_templates_updated_at (updated_at)
);
