server.error.include-message=never

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.cache.type=redis

logging.level.com.mixmaster.platform=INFO
logging.level.org.springframework.security=INFO

mixmaster.security.bootstrap.enabled=false
mixmaster.security.token.enabled=false
